apiVersion : apps/v1
kind: Deployment
metadata:
  name: dalavayiacrbuildhelloworldnode 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dalavayiacrbuildhelloworldnode
  template:
    metadata:
      labels:
        app: dalavayiacrbuildhelloworldnode 
    spec:
      containers:
        - name: dalavayiacrbuildhelloworldnode 
          image: mlopsapi.azurecr.io/dalavayiacrbuildhelloworldnode
          ports:
          - containerPort: 80